name: Static Analysis using Flake8

on: 
  push:
    branches: 
      - main

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    # Run flake8 on the shopping_cart.py script
    - name: Run static analysis
      run: |
        flake8 shopping_cart.py
        
  unit-testing:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    # Run unit tests
    - name: Run unit tests
      run: |
        python -m unittest tests.py